function ROTOR_STATUS_all = importfile_ROTOR_STATUS(filename)
%IMPORTFILE Import data from a text file
%  ROTORSUMMARYT52300030935 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the numeric data.
%
%  ROTORSUMMARYT52300030935 = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  ROTORSUMMARYT52300030935 = importfile("C:\Users\capplor01\Downloads\NEOM_v05_reference\ROTOR_SUMMARY_T52_300_030_935.txt", [5, 5]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-May-2024 16:31:58

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [5, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ":";

% Specify column names and types
opts.VariableNames = ["Var1", "NEOM_BCL809"];
opts.SelectedVariableNames = "NEOM_BCL809";
opts.VariableTypes = ["string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "NEOM_BCL809", "TrimNonNumeric", true);
opts = setvaropts(opts, "NEOM_BCL809", "ThousandsSeparator", ",");

% Import the data
ROTORSUMMARYT52300030935 = readtable(filename, opts);

%% Convert to output type
ROTOR_STATUS_all = table2array(ROTORSUMMARYT52300030935);
% ROTOR_STATUS=ROTOR_STATUS_all(1,2);
end