function ALL_RES_SEC = import_ALL_RES_SEC(filename,nstep_tot)
%IMPORTFILE1 Import numeric data from a text file as a matrix.
%   ALLRESSEC1 = IMPORTFILE1(FILENAME) Reads data from text file FILENAME
%   for the default selection.
%
%   ALLRESSEC1 = IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads data from
%   rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   ALLRESSEC1 = importfile1('ALL_RES_SEC1.txt', 1, 21);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2023/02/09 11:22:41

%% Initialize variables.
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
% For more information, see the TEXTSCAN documentation.
% formatSpec = '%20f%20f%20f%20f%20f%f%[^\n\r]';
str_ref_format_ref='%f';
str_format=str_ref_format_ref;
for ww4=1:(nstep_tot)*3-1
    str_format = strcat(str_format,str_ref_format_ref);
end
str_format = strcat(str_format,'%[^\n\r]');
formatSpec=str_format;
%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
ALL_RES_SEC = [dataArray{1:end-1}];
