function def_dim_start = importfile_def_dim_start(filename)
%IMPORTFILE Import data from a text file
%  DEF_DIM_START = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  DEF_DIM_START = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  def_dim_start = importfile("C:\Users\capplor01\Downloads\NEOM_v05_reference\T52_207_030_D2_935_F22HT8\n_disk2\04_MATLAB_FCGR\T52_207_030_935_n_disk2_def_summary.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-May-2024 10:49:02

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "  ";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "VarName3", "Var4", "Var5", "VarName6"];
opts.SelectedVariableNames = ["VarName3", "VarName6"];
opts.VariableTypes = ["string", "string", "double", "string", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var4", "Var5"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var4", "Var5"], "EmptyFieldRule", "auto");

% Import the data
def_dim_start = readtable(filename, opts);

%% Convert to output type
def_dim_start = table2array(def_dim_start);
end